### ISSUE TITLE
LESS error

### ISSUE THREAD

**Issue by mateuszjarzewski** [drew-r/bootstrap-n-column#1]
SyntaxError: expected expression
in bootstrap.less on line 80, column 40:

79  .col-@{numCols} {
80      .cols-xs (@colIdx) when (@colIdx <= @numCols) {
81          >.col-xs-@{colIdx} {

**Comment by drew-r** [comment]
Thanks! That was a dumb error. 
Fixed in https://github.com/drew-r/bootstrap-n-column/commit/5bed9f4bec6e155d6f798eda9c169486551bc682

Closing
