### ISSUE TITLE
File not present: styles.css

### ISSUE THREAD

**Issue by edsonlb** [drew-r/bootstrap-n-column#5]
Hi @drew-r ,
This repo does not include "styles.css" file. Can you upload to the project ?

```
<!-- example requires bootstrap-n-column.less to be compiled to styles.css -->
<link rel="stylesheet" href="styles.css">
```

Thank you, and good job!
@edsonlb

**Comment by Silverium** [comment]
seriously, you need to learn what is [LESS](http://lesscss.org/) and close this issue right now

**Comment by emmgfx** [comment]
@edsonlb this code can't be used as CSS directly. You should use this code in your less code and then, compile it.

**Comment by edsonlb** [comment]
@emmgfx, Thank you so much for your kind response.
